use std::collections::{BTreeMap, BTreeSet};
use crate::systems::wccs::ast::{Binding, Process, WeightedAction, Action, Relabeling};
use lalrpop_util::ParseError;
use crate::systems::numeric::Number;

grammar;

pub Program: Vec<Binding<'input>> = (<Binding> ";")*;


Binding: Binding<'input> = {
  <name:Id> ":=" <process:Process> => Binding { name, process },
}

pub Process: Process<'input> = SummationProcess;

SummationProcess: Process<'input> = {
  <l:CompositionProcess> "+" <r:SummationProcess> => Process::Sum(Box::new(l), Box::new(r)),
  CompositionProcess,
}

CompositionProcess: Process<'input> = {
  <l:AtomicPropositionProcess> "|" <r:CompositionProcess> => Process::Compose(Box::new(l), Box::new(r)),
  AtomicPropositionProcess,
}

AtomicPropositionProcess: Process<'input> = {
    <labels:(<Label> ":")+> <process:ActionPrefixProcess> => Process::AtomicPropositions {
        propositions: labels.into_iter().collect(),
        process: Box::new(process),
    },
    ActionPrefixProcess
}

ActionPrefixProcess: Process<'input> = {
    <action:Action> "." <process:AtomicPropositionProcess> => Process::ActionPrefix {action, process: Box::new(process)},
    RelabeledProcess,
}


RelabeledProcess: Process<'input> = {
    <process:RelabeledProcess> "[" <relabelings:Comma<Relabelling>> "]" =>? {
        if relabelings.iter().all(|x| matches!(x, Relabeling::Action(l, r))) {
            let pairs: Vec<_> = relabelings.into_iter().map(|x| match x {
                Relabeling::Action(from, to) => (from, to),
                _ => unreachable!("All relabelings should apply to actions"),
            }).collect();
            if pairs.iter().any(|(from, to)| *from == "tau" || *to == "tau") {
                Err(ParseError::User {
                error: "cannot relabel tau"
                })
            } else {
                Ok(Process::ActionRelabelling {
                process: Box::new(process),
                labels: BTreeMap::from_iter(pairs),
                })
            }
        } else if relabelings.iter().all(|x| matches!(x, Relabeling::Proposition(l, r))) {
            Ok(Process::PropositionRelabelling {
                process: Box::new(process),
                labels: BTreeMap::from_iter(relabelings.into_iter().map(|x| match x {
                    Relabeling::Proposition(from, to) => (from, to),
                    _ => unreachable!("All relabelings should apply to proposition"),
                }))
            })   
        }
        else {
            Err(ParseError::User {
                    error: "Proposition relabelings can not be combined with action relabelings"
            })
        }
    },
   

    RestrictedProcess,
}

RestrictedProcess: Process<'input> = {
  <process:RestrictedProcess> "\\" <restriction:LabelSet> => Process::Restriction {
      process: Box::new(process),
      restriction,
    },
  Paren
}

Paren: Process<'input> = {
  "(" <Process> ")",
  "0" => Process::Nil,
  <Id> => Process::Named(<>),
}

Relabelling: Relabeling<'input> = {
    <l:Label> "->" <r:Label> => Relabeling::Action(l, r),
    <l:Label> "=>" <r:Label> => Relabeling::Proposition(l, r),
};

PropositionRelabelling: (&'input str, &'input str) = <Label> "=>" <Label>;

LabelSet: BTreeSet<&'input str> = {
  "{" <labels:Comma<Label>> "}" =>? if labels.iter().any(|l| *l == "tau") {
    Err(ParseError::User {
      error: "tau is not allowed in label set"
    })
  } else {
    Ok(BTreeSet::from_iter(labels.into_iter()))
  },
}

pub Action: WeightedAction<'input> = {
    "<" <name:Label> <co:"!"?> <weight:(r", *[0-9]+")?> ">" =>? match name {
        "tau" => if co.is_some() {
                Err(ParseError::User {
                    error: "co tau action not allowed"
                })
            }
            else {
                Ok(WeightedAction {weight: Number::Val(weight.map(|s| s.trim_start_matches([',', ' ']).parse().expect("Weight should parse to int")).unwrap_or(0)), action: Action::Tau})
            },

        name => Ok(WeightedAction {
            weight: Number::Val(weight
                    .map(|s| 
                        s.trim_start_matches([',', ' ']).parse().expect("Weight should parse to int"))
                    .unwrap_or(0)), 
            action: Action::Label {
                name,
                is_complement: co.is_some(),
            },
        }),
   },
}


Label: &'input str = <r"[a-z][A-Za-z0-9?_']*">;

Id: &'input str = <r"[A-Z][A-Za-z0-9_']*">;

Num: Number = {
    <s:r"[0-9]+"> => Number::Val(s.parse().expect("u32 should parse strings")),
    "inf" => Number::Inf,
} 

Comma<T>: Vec<T> = {
    <mut v:(<T> ",")*> <e:T?> => match e {
        None => v,
        Some(e) => {
            v.push(e);
            v
        }
    }
};


match {
    r"\s*" => {}, // whitespace
    r"\#[^\n\r]*[\n\r]*" => {}, // `* comments`
    _
}